### ISSUE TITLE
Broken link for geographic projections information

### ISSUE THREAD

**Issue by jni** [altair-viz/altair-viz.github.io#15]
I get a 404 on this page:

https://altair-viz.github.io/user_guide/projection.html

linked to from this page:

https://altair-viz.github.io/user_guide/configuration.html

**Comment by jni** [comment]
(Incidentally what I'm looking for is how to set a crop/zoom to see only a particular lat/lon rectangle on the plot, if someone has an example handy... ;)

**Comment by jakevdp** [comment]
Thanks – this is a known issue: see https://github.com/altair-viz/altair/issues/791

**Comment by jni** [comment]
Ah! Thanks! I looked for "projection" to try to find this on the Altair docs, so perhaps adding this URL to that issue would help.
