### ISSUE TITLE
DOC: Gallery: How to open interactive charts

### ISSUE THREAD

**Issue by westurner** [altair-viz/altair-viz.github.io#21]
How do I open these interactive charts? (Why don't they work in Sphinx? Is Launch in Binder the best or only way to open them?)

https://altair-viz.github.io/gallery/index.html#interactive-charts

**Comment by jakevdp** [comment]
You can open them directly on that page by clicking on the thumbnails – Altair charts don't require a Python backend.

If you want to use Altair charts in sphinx, you can use the ``altair-plot`` directive available here: https://github.com/altair-viz/altair/blob/master/altair/sphinxext/altairplot.py

This is what Altair's documentation uses to embed interactive charts.

**Comment by westurner** [comment]
My mistake! They *are* interactive in Sphinx. Thanks!
