### ISSUE TITLE
Layered Histogram example does not take into account null values

### ISSUE THREAD

**Issue by harabat** [altair-viz/altair-viz.github.io#25]
## Issue

This is based on the issue [#2411](https://github.com/altair-viz/altair/issues/2411) that I originally posted in the `altair` repo. 

The method for making layered histograms [suggested on altair-viz.github.io](https://altair-viz.github.io/gallery/layered_histogram.html) seems to fail to take into account null values within the range of the data: bins that should be empty are represented as having 1 observation. 

---

## Examples

Altair:
```python
import pandas as pd
import altair as alt
import numpy as np

np.random.seed(42)

# Generating Data
source = pd.DataFrame({
    'Trial A': np.random.normal(0, 0.8, 1000),
    'Trial B': np.random.normal(-2, 1, 1000),
    'Trial C': np.random.normal(3, 2, 1000)
})

alt.Chart(source).transform_fold(
    ['Trial A', 'Trial B', 'Trial C'],
    as_=['Experiment', 'Measurement']
).mark_area(
    opacity=0.3,
    interpolate='step'
).encode(
    alt.X('Measurement:Q', bin=alt.Bin(maxbins=100)),
    alt.Y('count()', stack=None),
    alt.Color('Experiment:N')
)
```
![layered_histogram_altair](https://user-images.githubusercontent.com/45575009/108603170-45eb2f00-739e-11eb-88fe-0b1468d33a1c.png)

---

## Solution

The suggested method should be `mark_bar` instead of `mark_area`, which correctly represents the data. I'll be doing a PR shortly. 

![layered_histogram_altair_solution](https://user-images.githubusercontent.com/45575009/108626793-ed716b80-7449-11eb-843b-65d60e5673ad.png)

The underlying issue with `mark_area` still needs fixing however: here's how it looks in Seaborn:

![layered_histogram_seaborn](https://user-images.githubusercontent.com/45575009/108603174-4b487980-739e-11eb-9db2-c52d958f6297.png)

Should I open the issue in https://github.com/vega/vega-lite?

**Comment by jakevdp** [comment]
Closing in favor of https://github.com/altair-viz/altair/issues/2411
