### ISSUE TITLE
properties() method not documented

### ISSUE THREAD

**Issue by mcp292** [altair-viz/altair-viz.github.io#26]
I'm reading through [Encodings](https://altair-viz.github.io/user_guide/encoding.html) and noticed the awesome `properties()` method.

Where do I find documentation on this?

I would have expected first mention of it to be hyperlinked. It does not come up in searches on the docs page

**Comment by jakevdp** [comment]
Thanks for the question – the `properties` method is used to set top-level object properties. It is mentioned in the docs [here](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html), and you can find examples of its use throughout the documentation. Does that help?

**Comment by mcp292** [comment]
Very much so! Thank you!

Before I close the issue, what in my workflow was flawed? Was there a better away to arrive at the page  you linked? What prevented my search from pulling it up?

**Comment by mcp292** [comment]
Also, I'm noticing now that it just has `**kwargs` for the params. Where would I find this spelled out?

Really I'm in search of what params `properties()` takes.

**Comment by jakevdp** [comment]
`properties` takes as arguments any of the attributes defined on the object from which you call it.

So, for example, `alt.Chart.properties` takes any argument that `alt.Chart` does, and returns a copy of the chart with those properties set.

**Comment by mcp292** [comment]
Ah! That does it! Thanks again!
